# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.dict_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u7ec4\u540d')),
                ('title', models.CharField(max_length=100, verbose_name='\u7ec4\u6807\u9898')),
                ('members', models.ManyToManyField(blank=True, related_name='belong_groups', to=settings.AUTH_USER_MODEL, verbose_name='\u7ec4\u5185\u6210\u5458')),
            ],
            options={
                'db_table': 'tb_role',
            },
            bases=(utils.dict_mixin.DictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackendModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u6a21\u5757\u540d')),
                ('title', models.CharField(max_length=100, verbose_name='\u6a21\u5757\u540d\u79f0')),
            ],
            options={
                'db_table': 'tb_model',
            },
            bases=(utils.dict_mixin.DictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackendPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6743\u9650\u540d')),
                ('title', models.CharField(max_length=100, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.BackendModule', verbose_name='\u6240\u5c5e\u6a21\u5757')),
            ],
            options={
                'db_table': 'tb_permission',
            },
            bases=(utils.dict_mixin.DictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='backendgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='backend.BackendPermission'),
        ),
    ]
